//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartCtrl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ChartStyle {
            get {
                return ((int)(this["ChartStyle"]));
            }
            set {
                this["ChartStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RtTimeType {
            get {
                return ((int)(this["RtTimeType"]));
            }
            set {
                this["RtTimeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RtTimeUnit {
            get {
                return ((int)(this["RtTimeUnit"]));
            }
            set {
                this["RtTimeUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DtTimeType {
            get {
                return ((int)(this["DtTimeType"]));
            }
            set {
                this["DtTimeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DtTimeUnit {
            get {
                return ((int)(this["DtTimeUnit"]));
            }
            set {
                this["DtTimeUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AvgLineWidth {
            get {
                return ((int)(this["AvgLineWidth"]));
            }
            set {
                this["AvgLineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AvgLine {
            get {
                return ((bool)(this["AvgLine"]));
            }
            set {
                this["AvgLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fuchsia")]
        public global::System.Drawing.Color AvgLineColor1 {
            get {
                return ((global::System.Drawing.Color)(this["AvgLineColor1"]));
            }
            set {
                this["AvgLineColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color AvgLineColor2 {
            get {
                return ((global::System.Drawing.Color)(this["AvgLineColor2"]));
            }
            set {
                this["AvgLineColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color AvgLineColor3 {
            get {
                return ((global::System.Drawing.Color)(this["AvgLineColor3"]));
            }
            set {
                this["AvgLineColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color AvgLineColor4 {
            get {
                return ((global::System.Drawing.Color)(this["AvgLineColor4"]));
            }
            set {
                this["AvgLineColor4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color AvgLineColor5 {
            get {
                return ((global::System.Drawing.Color)(this["AvgLineColor5"]));
            }
            set {
                this["AvgLineColor5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BoLine {
            get {
                return ((bool)(this["BoLine"]));
            }
            set {
                this["BoLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color BoLineColor1 {
            get {
                return ((global::System.Drawing.Color)(this["BoLineColor1"]));
            }
            set {
                this["BoLineColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color BoLineColor2 {
            get {
                return ((global::System.Drawing.Color)(this["BoLineColor2"]));
            }
            set {
                this["BoLineColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BoLineAdjustR {
            get {
                return ((int)(this["BoLineAdjustR"]));
            }
            set {
                this["BoLineAdjustR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BoLineAdjustD {
            get {
                return ((int)(this["BoLineAdjustD"]));
            }
            set {
                this["BoLineAdjustD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color AvgLineColor6 {
            get {
                return ((global::System.Drawing.Color)(this["AvgLineColor6"]));
            }
            set {
                this["AvgLineColor6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Avg5On {
            get {
                return ((bool)(this["Avg5On"]));
            }
            set {
                this["Avg5On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Avg10On {
            get {
                return ((bool)(this["Avg10On"]));
            }
            set {
                this["Avg10On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Avg20On {
            get {
                return ((bool)(this["Avg20On"]));
            }
            set {
                this["Avg20On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Avg60On {
            get {
                return ((bool)(this["Avg60On"]));
            }
            set {
                this["Avg60On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Avg120On {
            get {
                return ((bool)(this["Avg120On"]));
            }
            set {
                this["Avg120On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Avg200On {
            get {
                return ((bool)(this["Avg200On"]));
            }
            set {
                this["Avg200On"] = value;
            }
        }
    }
}
