//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuckyFuture.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoginId {
            get {
                return ((string)(this["LoginId"]));
            }
            set {
                this["LoginId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSaveLoginId {
            get {
                return ((bool)(this["IsSaveLoginId"]));
            }
            set {
                this["IsSaveLoginId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteId {
            get {
                return ((string)(this["SiteId"]));
            }
            set {
                this["SiteId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SitePassword {
            get {
                return ((string)(this["SitePassword"]));
            }
            set {
                this["SitePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LossStop {
            get {
                return ((bool)(this["LossStop"]));
            }
            set {
                this["LossStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EarnStop {
            get {
                return ((bool)(this["EarnStop"]));
            }
            set {
                this["EarnStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LossPayoff {
            get {
                return ((bool)(this["LossPayoff"]));
            }
            set {
                this["LossPayoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EarnPayoff {
            get {
                return ((bool)(this["EarnPayoff"]));
            }
            set {
                this["EarnPayoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int LossPayoffMoney {
            get {
                return ((int)(this["LossPayoffMoney"]));
            }
            set {
                this["LossPayoffMoney"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int EarnPayoffMoney {
            get {
                return ((int)(this["EarnPayoffMoney"]));
            }
            set {
                this["EarnPayoffMoney"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LossStopMoney {
            get {
                return ((int)(this["LossStopMoney"]));
            }
            set {
                this["LossStopMoney"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EarnStopMoney {
            get {
                return ((int)(this["EarnStopMoney"]));
            }
            set {
                this["EarnStopMoney"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int BettingCandleCount {
            get {
                return ((int)(this["BettingCandleCount"]));
            }
            set {
                this["BettingCandleCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoMode {
            get {
                return ((bool)(this["IsAutoMode"]));
            }
            set {
                this["IsAutoMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ChartType {
            get {
                return ((int)(this["ChartType"]));
            }
            set {
                this["ChartType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SiteType {
            get {
                return ((int)(this["SiteType"]));
            }
            set {
                this["SiteType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AvgType {
            get {
                return ((int)(this["AvgType"]));
            }
            set {
                this["AvgType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CandlePayoff {
            get {
                return ((bool)(this["CandlePayoff"]));
            }
            set {
                this["CandlePayoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CandlePayoffCount {
            get {
                return ((int)(this["CandlePayoffCount"]));
            }
            set {
                this["CandlePayoffCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int BettingType {
            get {
                return ((int)(this["BettingType"]));
            }
            set {
                this["BettingType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int BettingTickCount {
            get {
                return ((int)(this["BettingTickCount"]));
            }
            set {
                this["BettingTickCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TickPayoffCount {
            get {
                return ((int)(this["TickPayoffCount"]));
            }
            set {
                this["TickPayoffCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OrderStop {
            get {
                return ((bool)(this["OrderStop"]));
            }
            set {
                this["OrderStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int OrderStopDelay {
            get {
                return ((int)(this["OrderStopDelay"]));
            }
            set {
                this["OrderStopDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BettingCandleComplete {
            get {
                return ((int)(this["BettingCandleComplete"]));
            }
            set {
                this["BettingCandleComplete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float OrderCount {
            get {
                return ((float)(this["OrderCount"]));
            }
            set {
                this["OrderCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OrderType {
            get {
                return ((int)(this["OrderType"]));
            }
            set {
                this["OrderType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int OrderMax {
            get {
                return ((int)(this["OrderMax"]));
            }
            set {
                this["OrderMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reorder {
            get {
                return ((bool)(this["Reorder"]));
            }
            set {
                this["Reorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ServerTimeDelay {
            get {
                return ((int)(this["ServerTimeDelay"]));
            }
            set {
                this["ServerTimeDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BoLineAdjust {
            get {
                return ((int)(this["BoLineAdjust"]));
            }
            set {
                this["BoLineAdjust"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BettingEnter {
            get {
                return ((bool)(this["BettingEnter"]));
            }
            set {
                this["BettingEnter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LiquidStop {
            get {
                return ((bool)(this["LiquidStop"]));
            }
            set {
                this["LiquidStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public float ItemOverTick {
            get {
                return ((float)(this["ItemOverTick"]));
            }
            set {
                this["ItemOverTick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0:0.00}")]
        public string PriceFormat {
            get {
                return ((string)(this["PriceFormat"]));
            }
            set {
                this["PriceFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForceEarnPayoff {
            get {
                return ((bool)(this["ForceEarnPayoff"]));
            }
            set {
                this["ForceEarnPayoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SmartLossPayoff {
            get {
                return ((bool)(this["SmartLossPayoff"]));
            }
            set {
                this["SmartLossPayoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BandChart {
            get {
                return ((bool)(this["BandChart"]));
            }
            set {
                this["BandChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BandVal1 {
            get {
                return ((int)(this["BandVal1"]));
            }
            set {
                this["BandVal1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BandVal2 {
            get {
                return ((int)(this["BandVal2"]));
            }
            set {
                this["BandVal2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BandChartType1 {
            get {
                return ((int)(this["BandChartType1"]));
            }
            set {
                this["BandChartType1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BandChartType2 {
            get {
                return ((int)(this["BandChartType2"]));
            }
            set {
                this["BandChartType2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BandChartType3 {
            get {
                return ((int)(this["BandChartType3"]));
            }
            set {
                this["BandChartType3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BandChartType4 {
            get {
                return ((int)(this["BandChartType4"]));
            }
            set {
                this["BandChartType4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BandVal3 {
            get {
                return ((int)(this["BandVal3"]));
            }
            set {
                this["BandVal3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SmartEarnTick {
            get {
                return ((int)(this["SmartEarnTick"]));
            }
            set {
                this["SmartEarnTick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SmartLossTick {
            get {
                return ((int)(this["SmartLossTick"]));
            }
            set {
                this["SmartLossTick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SmartLossUnit {
            get {
                return ((int)(this["SmartLossUnit"]));
            }
            set {
                this["SmartLossUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7kWqr0Doi2YdYmxqEFoX3g==")]
        public string LockPwd {
            get {
                return ((string)(this["LockPwd"]));
            }
            set {
                this["LockPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CrossLossPayoff {
            get {
                return ((bool)(this["CrossLossPayoff"]));
            }
            set {
                this["CrossLossPayoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CrossLossTick {
            get {
                return ((int)(this["CrossLossTick"]));
            }
            set {
                this["CrossLossTick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CrossLossUnit {
            get {
                return ((int)(this["CrossLossUnit"]));
            }
            set {
                this["CrossLossUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlarmStop {
            get {
                return ((bool)(this["AlarmStop"]));
            }
            set {
                this["AlarmStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InformStop {
            get {
                return ((bool)(this["InformStop"]));
            }
            set {
                this["InformStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChkNoticeDay {
            get {
                return ((bool)(this["ChkNoticeDay"]));
            }
            set {
                this["ChkNoticeDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime NoticeViewTime {
            get {
                return ((global::System.DateTime)(this["NoticeViewTime"]));
            }
            set {
                this["NoticeViewTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EarnPayoffN {
            get {
                return ((bool)(this["EarnPayoffN"]));
            }
            set {
                this["EarnPayoffN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EarnPayoffMoneyN {
            get {
                return ((int)(this["EarnPayoffMoneyN"]));
            }
            set {
                this["EarnPayoffMoneyN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LossPayoffN {
            get {
                return ((bool)(this["LossPayoffN"]));
            }
            set {
                this["LossPayoffN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LossPayoffMoneyN {
            get {
                return ((int)(this["LossPayoffMoneyN"]));
            }
            set {
                this["LossPayoffMoneyN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OrderSelectOn {
            get {
                return ((bool)(this["OrderSelectOn"]));
            }
            set {
                this["OrderSelectOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OrderSelectType {
            get {
                return ((int)(this["OrderSelectType"]));
            }
            set {
                this["OrderSelectType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime StartChartDt {
            get {
                return ((global::System.DateTime)(this["StartChartDt"]));
            }
            set {
                this["StartChartDt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2023-09-04")]
        public global::System.DateTime AutoReserveTime {
            get {
                return ((global::System.DateTime)(this["AutoReserveTime"]));
            }
            set {
                this["AutoReserveTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoReserveOn {
            get {
                return ((bool)(this["AutoReserveOn"]));
            }
            set {
                this["AutoReserveOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProfitStop {
            get {
                return ((bool)(this["ProfitStop"]));
            }
            set {
                this["ProfitStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProfitStopRate {
            get {
                return ((int)(this["ProfitStopRate"]));
            }
            set {
                this["ProfitStopRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Conc1On {
            get {
                return ((bool)(this["Conc1On"]));
            }
            set {
                this["Conc1On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Conc1Min {
            get {
                return ((int)(this["Conc1Min"]));
            }
            set {
                this["Conc1Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Conc1Cnt {
            get {
                return ((int)(this["Conc1Cnt"]));
            }
            set {
                this["Conc1Cnt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Conc2On {
            get {
                return ((bool)(this["Conc2On"]));
            }
            set {
                this["Conc2On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Conc2Chart {
            get {
                return ((int)(this["Conc2Chart"]));
            }
            set {
                this["Conc2Chart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Conc2Candle {
            get {
                return ((int)(this["Conc2Candle"]));
            }
            set {
                this["Conc2Candle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Conc2Cnt {
            get {
                return ((int)(this["Conc2Cnt"]));
            }
            set {
                this["Conc2Cnt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdxOn {
            get {
                return ((bool)(this["AdxOn"]));
            }
            set {
                this["AdxOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AdxCnt {
            get {
                return ((int)(this["AdxCnt"]));
            }
            set {
                this["AdxCnt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SmartRangePayoff {
            get {
                return ((bool)(this["SmartRangePayoff"]));
            }
            set {
                this["SmartRangePayoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CrossRangePayoff {
            get {
                return ((bool)(this["CrossRangePayoff"]));
            }
            set {
                this["CrossRangePayoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SignalSiteOn {
            get {
                return ((bool)(this["SignalSiteOn"]));
            }
            set {
                this["SignalSiteOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CciOn {
            get {
                return ((bool)(this["CciOn"]));
            }
            set {
                this["CciOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CciRange1 {
            get {
                return ((int)(this["CciRange1"]));
            }
            set {
                this["CciRange1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CciRange2 {
            get {
                return ((int)(this["CciRange2"]));
            }
            set {
                this["CciRange2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CciSide1 {
            get {
                return ((int)(this["CciSide1"]));
            }
            set {
                this["CciSide1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CciSide2 {
            get {
                return ((int)(this["CciSide2"]));
            }
            set {
                this["CciSide2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RsiOn {
            get {
                return ((bool)(this["RsiOn"]));
            }
            set {
                this["RsiOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RsiRange1 {
            get {
                return ((int)(this["RsiRange1"]));
            }
            set {
                this["RsiRange1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RsiRange2 {
            get {
                return ((int)(this["RsiRange2"]));
            }
            set {
                this["RsiRange2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RsiSide1 {
            get {
                return ((int)(this["RsiSide1"]));
            }
            set {
                this["RsiSide1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RsiSide2 {
            get {
                return ((int)(this["RsiSide2"]));
            }
            set {
                this["RsiSide2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AvgsOn {
            get {
                return ((bool)(this["AvgsOn"]));
            }
            set {
                this["AvgsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AvgsCandle {
            get {
                return ((int)(this["AvgsCandle"]));
            }
            set {
                this["AvgsCandle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AvgsSide1 {
            get {
                return ((int)(this["AvgsSide1"]));
            }
            set {
                this["AvgsSide1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AvgsSide2 {
            get {
                return ((int)(this["AvgsSide2"]));
            }
            set {
                this["AvgsSide2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LossRangePayoff {
            get {
                return ((bool)(this["LossRangePayoff"]));
            }
            set {
                this["LossRangePayoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CciPayoff {
            get {
                return ((bool)(this["CciPayoff"]));
            }
            set {
                this["CciPayoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CciPayoffValue1 {
            get {
                return ((int)(this["CciPayoffValue1"]));
            }
            set {
                this["CciPayoffValue1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CciRangePayoff {
            get {
                return ((bool)(this["CciRangePayoff"]));
            }
            set {
                this["CciRangePayoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CciPayoffValue2 {
            get {
                return ((int)(this["CciPayoffValue2"]));
            }
            set {
                this["CciPayoffValue2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1#0.2#0.5#1")]
        public string OrdCnts {
            get {
                return ((string)(this["OrdCnts"]));
            }
            set {
                this["OrdCnts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200#400#800#1000")]
        public string EarnTicks {
            get {
                return ((string)(this["EarnTicks"]));
            }
            set {
                this["EarnTicks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200#400#800#1000")]
        public string LossTicks {
            get {
                return ((string)(this["LossTicks"]));
            }
            set {
                this["LossTicks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BoOrdType {
            get {
                return ((int)(this["BoOrdType"]));
            }
            set {
                this["BoOrdType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CciPayoffValue3 {
            get {
                return ((int)(this["CciPayoffValue3"]));
            }
            set {
                this["CciPayoffValue3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CciRange11 {
            get {
                return ((int)(this["CciRange11"]));
            }
            set {
                this["CciRange11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CciRange21 {
            get {
                return ((int)(this["CciRange21"]));
            }
            set {
                this["CciRange21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SyncMembers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SyncMembers"]));
            }
            set {
                this["SyncMembers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyncChart {
            get {
                return ((bool)(this["SyncChart"]));
            }
            set {
                this["SyncChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>1#0#50#0#0</string>
  <string>1#10#40#0#0</string>
  <string>1#30#30#0#0</string>
  <string>1#50#20#0#0</string>
  <string>1#70#10#0#0</string>
  <string>1#100#5#0#0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PayoffLossRange {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PayoffLossRange"]));
            }
            set {
                this["PayoffLossRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>1#10#50#50#30</string>
  <string>1#20#45#50#30</string>
  <string>1#30#40#50#30</string>
  <string>1#40#35#50#30</string>
  <string>1#50#30#50#30</string>
  <string>1#60#25#50#30</string>
  <string>1#70#20#50#30</string>
  <string>1#80#15#50#30</string>
  <string>1#90#10#50#30</string>
  <string>1#100#5#50#30</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SmartLossRange {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SmartLossRange"]));
            }
            set {
                this["SmartLossRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>1#10#50#50#30</string>
  <string>1#20#45#50#30</string>
  <string>1#30#40#50#30</string>
  <string>1#40#35#50#30</string>
  <string>1#50#30#50#30</string>
  <string>1#60#25#50#30</string>
  <string>1#70#20#50#30</string>
  <string>1#80#15#50#30</string>
  <string>1#90#10#50#30</string>
  <string>1#100#5#50#30</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CrossLossRange {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CrossLossRange"]));
            }
            set {
                this["CrossLossRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>1#100#50#50#30</string>
  <string>1#150#40#50#30</string>
  <string>1#200#30#50#30</string>
  <string>1#250#20#50#30</string>
  <string>1#300#10#50#30</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CciLossRange {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CciLossRange"]));
            }
            set {
                this["CciLossRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BollPayoff {
            get {
                return ((bool)(this["BollPayoff"]));
            }
            set {
                this["BollPayoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float BollPayoffDown {
            get {
                return ((float)(this["BollPayoffDown"]));
            }
            set {
                this["BollPayoffDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float BollPayoffUp {
            get {
                return ((float)(this["BollPayoffUp"]));
            }
            set {
                this["BollPayoffUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MacdPayoff {
            get {
                return ((bool)(this["MacdPayoff"]));
            }
            set {
                this["MacdPayoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BothOrder {
            get {
                return ((bool)(this["BothOrder"]));
            }
            set {
                this["BothOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte ReturnOption {
            get {
                return ((byte)(this["ReturnOption"]));
            }
            set {
                this["ReturnOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PayoffWithEarn {
            get {
                return ((bool)(this["PayoffWithEarn"]));
            }
            set {
                this["PayoffWithEarn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CrossAvgLine1 {
            get {
                return ((int)(this["CrossAvgLine1"]));
            }
            set {
                this["CrossAvgLine1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CrossAvgLine2 {
            get {
                return ((int)(this["CrossAvgLine2"]));
            }
            set {
                this["CrossAvgLine2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReverseOrder {
            get {
                return ((bool)(this["ReverseOrder"]));
            }
            set {
                this["ReverseOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ReverseOrdCnt1 {
            get {
                return ((int)(this["ReverseOrdCnt1"]));
            }
            set {
                this["ReverseOrdCnt1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ReverseOrdSel1 {
            get {
                return ((int)(this["ReverseOrdSel1"]));
            }
            set {
                this["ReverseOrdSel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ReverseOrdCnt2 {
            get {
                return ((int)(this["ReverseOrdCnt2"]));
            }
            set {
                this["ReverseOrdCnt2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReverseOrdSel2 {
            get {
                return ((int)(this["ReverseOrdSel2"]));
            }
            set {
                this["ReverseOrdSel2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GapLiquid {
            get {
                return ((bool)(this["GapLiquid"]));
            }
            set {
                this["GapLiquid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GapValue {
            get {
                return ((int)(this["GapValue"]));
            }
            set {
                this["GapValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BoAdjustPerOn {
            get {
                return ((bool)(this["BoAdjustPerOn"]));
            }
            set {
                this["BoAdjustPerOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BoAdjustSecOn {
            get {
                return ((bool)(this["BoAdjustSecOn"]));
            }
            set {
                this["BoAdjustSecOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BoAdjustSec {
            get {
                return ((int)(this["BoAdjustSec"]));
            }
            set {
                this["BoAdjustSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte ReturnSBOption {
            get {
                return ((byte)(this["ReturnSBOption"]));
            }
            set {
                this["ReturnSBOption"] = value;
            }
        }
    }
}
